# Only works when inline
spring.application.name: springapp

springdoc:
  api-docs:
    path: /api-docs

spring:
  main:
    banner-mode: log
  profiles:
    active: prod
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springapp?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

server:
  tomcat:
    basedir: springapp/tomcat
  servlet:
    session:
      persistent: true
      store-dir: springapp
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

javamelody:
  init-parameters:
    log: true
    storage-directory: ${user.dir}/springapp/java-melody

management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: restart
